### ISSUE TITLE
Microphone

### ISSUE THREAD

**Issue by Anothermetrial** [zhujisheng/audio-reactive-led-strip#1]
Hi,

Very nice project
I want to build it, but kind of noob in electronics. I have this microphone:
https://www.robofun.ro/senzori/sunet/senzor-sunet-LM393 
Will it work with your code? 

Thank you

**Comment by zhujisheng** [comment]
It may work, but you have to modify the program. 
you can use the original  source with a digital PDM  microphone module, without any program modification.

**Comment by Anothermetrial** [comment]
I understand is a lot to ask, but I will try: Would you consider modifying the code to work with this very common microphone module?
If would be very helpful for a lot of other enthuziasts out there (including myself).

Thank you for considering this. Regards.

**Comment by zhujisheng** [comment]
I think the digital microphone is the trends. I have no plan to modify the code to work with analog microphone.
You can buy the module at: [https://lw.hachina.io/](https://lw.hachina.io/)

**Comment by phdelodder** [comment]
I also have an LM393, might look in to changing the code to work with it. 

This line:  unsigned int read_num;
                i2s_read(I2S_NUM_0, l, BUFFER_SIZE * 2, &read_num, portMAX_DELAY); 
needs to change to use an analog read. 

When I have all the parts I'll look in to it.

**Comment by Anothermetrial** [comment]
Hi. I used this microphone - is it correct?  https://www.optimusdigital.ro/ro/audio-altele/4774-modul-microfon-pdm-mems-adafruit.html

HA+Esphome - all libraries included, working with rainbow and plain color, but when choosing music 
 effects the leds are playing even if silence in the room. Pls let me know what am I doing wrong.
Regards

**Comment by phdelodder** [comment]
I just bought this module on https://nl.aliexpress.com/item/33011018502.html?spm=a2g0s.9042311.0.0.55544c4dmq8hL1 do you think it will work?

**Comment by Anothermetrial** [comment]
phdelodder - have you succeed with the mentioned microphone?

**Comment by phdelodder** [comment]
@Anothermetrial 
Changes for the I2S mircophone: https://github.com/phdelodder/audio-reactive-led-strip

**Comment by Anothermetrial** [comment]
Can you please validate my wiring of the mic please? it is my last try with the PDM before going to IS2.
The sympthom is: the 3 music effects are kind of running without any sound.
![20190927_124550](https://user-images.githubusercontent.com/47782990/65761520-974eaa80-e127-11e9-8e64-bae1c42e856c.jpg)

**Comment by Anothermetrial** [comment]
Thank you! Great job! Congrats!

**Comment by phdelodder** [comment]
@Anothermetrial you got it all working?

**Comment by Anothermetrial** [comment]
Hi,
I got it to work with the PDM as (stupid me) had a cold welding on the
mic's data pin. But i will redo the project with is2 microphone as the PDM
is too sensitive - even walking in the room is lighting my leds. I see that
is2 mic (from my first link) has a screw to reduce the sensitivity.
I will let you know the outcome first hand.

Regards
