### ISSUE TITLE
Unable to compile esphome

### ISSUE THREAD

**Issue by phdelodder** [zhujisheng/audio-reactive-led-strip#2]
ESPhome is not picking up the includes folder in the config of esphome

```
In file included from src/main.cpp:36:0:
src/music_leds_esphome.h:5:26: fatal error: includes/FFT.h: No such file or directory
#include "includes/FFT.h"
^
compilation terminated.
```

Followed the instructions in the readme

**Comment by zhujisheng** [comment]
git clone https://github.com/zhujisheng/audio-reactive-led-strip
cp -r audio-reactive-led-strip/includes/ ~/esphome_config/
cp audio-reactive-led-strip/music_leds_esphome.h ~/esphome_config/

Step2 above will copy the FFT.h into esphome_config/includes/

**Comment by phdelodder** [comment]
I have these files in my esphome folder: 

➜ ls ~/docker/config/esphome/includes
ExpFilter.h  FFT.h  gaussian_filter1d.h  VisualEffect.h

Still can 't get it to be picked up.

**Comment by zhujisheng** [comment]
The structure should be as below:
```
esphome-config-dir/your_esphome_config_file.yaml
esphome-config-dir/music_leds_esphome.h
esphome-config-dir/includes/xxxxx.h（4 files）

```

**Comment by zhujisheng** [comment]
Ok, It's my mistake.
The new esphome version, has changed the file structure.
Now you have to put them under dir `esphome-config-dir/your_esphome_config_name/src/includes/`

**Comment by zhujisheng** [comment]
I have commit new music_leds_esphome.h and new includes in the config yaml. @phdelodder 
Thanks.

**Comment by phdelodder** [comment]
Thanks works perfect!
