### ISSUE TITLE
Not working on 1.14.2 ESPHome

### ISSUE THREAD

**Issue by phdelodder** [zhujisheng/audio-reactive-led-strip#3]
I have upgraded to ESPHome 1.14.2, since then the reactive code doesn't work.

**Comment by zhujisheng** [comment]
Can you describe the error detailed? I have tried compiling it on esphome1.24.3, it's all OK.

**Comment by phdelodder** [comment]
The code does compile, however the reactive code isn't working like it expected to be.

**Comment by zhujisheng** [comment]
I think it's not related to the esphome's version.
You should check the connections or something else.
