### ISSUE TITLE
ESP8266 + Arduino Microphone?

### ISSUE THREAD

**Issue by marcinbauer-ohf** [zhujisheng/audio-reactive-led-strip#4]
Can this project be made to work on a 8266 board (D1 MINI for instance) and an arduino sound sensor?
(example: https://nl.aliexpress.com/item/32992611988.html?spm=a2g0o.productlist.0.0.6b0f3a724DEZ8I&s=p&algo_pvid=fdc0a0bf-7a3d-461d-8ccc-8ded059bd7f1&algo_expid=fdc0a0bf-7a3d-461d-8ccc-8ded059bd7f1-1&btsid=565bba61-f961-436c-825f-c00c3fdacf31&ws_ab_test=searchweb0_0,searchweb201602_5,searchweb201603_53)

Thanks!

**Comment by zhujisheng** [comment]
The esp32 is more powerful than 8266. I have tried on 8266, it's too slow, because the fft is computed on the chip.
