### ISSUE TITLE
Implementation for I2S microphone AND analog audio input?

### ISSUE THREAD

**Issue by ThePureCC** [zhujisheng/audio-reactive-led-strip#5]
Would you consider implementing the code for I2S microphones and give options like:

select_mic = "i2s" // or "PDM" 

-----

And would you consider implementing audio processing through analog audio inputs to ESP32?

-----
These would be two very useful features for the program. 

Thanks in advance.

**Comment by zhujisheng** [comment]
you can try following code for the I2S:
```c++
i2s_config_t i2s_config = {
  .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_RX),
  .sample_rate = SAMPLE_RATE,
  .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
  .channel_format = I2S_CHANNEL_FMT_ONLY_RIGHT,
  .communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_I2S | I2S_COMM_FORMAT_I2S_MSB),
  .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,
  .dma_buf_count = 32,
  .dma_buf_len = 32
};

i2s_pin_config_t pin_config = {
  .bck_io_num = 18,
  .ws_io_num = 19,
  .data_out_num = -1,
  .data_in_num = 22
};
```
The 18,19,22 is the three io connected to i2s.

**Comment by ThePureCC** [comment]
@zhujisheng Thank you for the reply. Do you have a solution for analog audio input? like a 3.5mm jack audio input for the ESP to process the audio, and manipulate the LEDs?

Much appreciated.

**Comment by Zack-Xu** [comment]
@pureche You may try some ADC chip which can transform analog audio input to PDM/I2S . For example , PCM1808 .
If equipped with a suitable circuit, the chip can convert the analog audio input into I2S signal. Then you can process the I2S signal on ESP32. 
If drawing a PCB is too difficult for you, you can  buy a module that already has peripheral circuits like these moudules.
![O1CN011RgA38ogaTeP3Kz_!!2820202140](https://user-images.githubusercontent.com/41894445/75215851-f58cc180-5789-11ea-85a2-67409a079ba0.jpg)
![O1CN01InvAcu1J5VU9XMYmb_!!1643150977](https://user-images.githubusercontent.com/41894445/75215756-a5156400-5789-11ea-9f02-c150768f7dda.jpg)

**Comment by ThePureCC** [comment]
@Zack-Xu Thank you for the reply. 

Doesn't ESP32 itself has ADC onboard? Is it possible to use the onboard ADC for the audio conversion? Like cutting the 3.5mm jack off, and connect the analog audio wires directly to ESP32's ADC pins? Would that work?

**Comment by Zack-Xu** [comment]
YES , It will work，but a chip will save you a lot of time of coding and the useage of CPU .  
I am a person who believes that things that can be solved with hardware is better than do it with software. : )

**Comment by ThePureCC** [comment]
Haha, good point. 

I'm only asking this because I would prefer as less hardware component as possible, to keep the package small, you know. Also saves power consumption if this thing were made mobile and powered by a LIPO battery. 

Would you consider adding native analog support to the project, please? I just don't know much about programming a ESP32 with audio related stuff.

**Comment by zhujisheng** [comment]
The hardware action codes only just below:

```c++
i2s_read(I2S_NUM_0, l, BUFFER_SIZE * 2, &read_num, portMAX_DELAY)
for (int i = 0; i < BUFFER_SIZE; i++) {
    y_data[BUFFER_SIZE * (N_ROLLING_HISTORY - 1) + i] = l[i] / 32768.0;
```
it read in BUFFER_SIZE data, and save it in y_data, all the datas are between(-1,1).

You can find these codes, and replace it with the some analog read codes. Pay attention to the sample rate —— you should control the frequency youself when read the analog pin.

**Comment by ThePureCC** [comment]
I'll see if I can figure this out on my own. If not, I'll let you know. Hope I could get some help then.

Thanks in advance.

**Comment by zhujisheng** [comment]
If you have this done, a PR is welcome
