### ISSUE TITLE
About buy Microphone Shield of HAChina.

### ISSUE THREAD

**Issue by imtoanle** [zhujisheng/audio-reactive-led-strip#6]
Hi

I'm from Vietnam. I tried to buy this shield from TaoBao but seller didn't reponse.
https://item.taobao.com/item.htm?ft=t&id=592861974901
Where i can buy this ?

Sorry for disturbing here but i couldn't find any contact channel.
Thanks

**Comment by Zack-Xu** [comment]
We're sorry to have kept you waiting for such a long time. 
At present, our products are not sold overseas. 
Can you provide an address in China where you can transfer your Express?So we can deliver it there.
