### ISSUE TITLE
Problems using esphome platform 

### ISSUE THREAD

**Issue by human2010** [zhujisheng/audio-reactive-led-strip#7]
According to your example, it can be used normally on the arduino platform, but there is no corresponding effect when using the esphome platform. Do you need to modify the music_leds_esphome.h file? 
（Have a certain C language foundation, but don’t know much about C++, please give me some advice! ）

**Comment by human2010** [comment]
Supplementary note: The WS2812 I currently use can use the lighting effects officially provided by esphome, but the custom music effects cannot work properly.

**Comment by zhujisheng** [comment]
There's no need to modify anything, except `num_leds` in configuration YAML, and `N_PIXELS` in `music_leds_esphome.h`.
Has the effect appeared in HomeAssistant? If you select musical effect, what happens? any error information or logs?
